"""Build the Lightspeed Windows installer and the portable zip.

Usage (from any shell, after `cmake --install`):
    python packaging/windows/make_installer.py [--build C:/lightspeed/build]
        [--install C:/lightspeed/install] [--iscc path/to/ISCC.exe] [--no-zip]

Writes dist/Lightspeed-<version>-win64-setup.exe and
dist/Lightspeed-<version>-win64-portable.zip next to the source tree.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, '..', '..'))
DIST = os.path.normpath(os.path.join(SRC, '..', 'dist'))


def cmake_cache(build):
    values = {}
    with open(os.path.join(build, 'CMakeCache.txt'), encoding='utf-8', errors='replace') as f:
        for line in f:
            m = re.match(r'^([A-Za-z0-9_]+):[A-Z]+=(.*)$', line.strip())
            if m:
                values[m.group(1)] = m.group(2)
    return values


def supported_extensions(build):
    # the configured darktable.iss lists every extension this build can read
    text = open(os.path.join(build, 'darktable.iss'), encoding='utf-8', errors='replace').read()
    exts = re.findall(r'Classes\\\.([A-Za-z0-9]+)\\OpenWithList', text)
    return sorted(set(e.lower() for e in exts))


def lightspeed_version():
    text = open(os.path.join(SRC, 'src', 'common', 'lightspeed_version.h'), encoding='utf-8').read()
    m = re.search(r'#define LIGHTSPEED_VERSION "([^"]+)"', text)
    v = m.group(1) if m else '1.0'
    return v if v.count('.') >= 2 else v + '.0'


def find_iscc(given):
    if given:
        return given
    for base in (os.environ.get('LOCALAPPDATA', ''), os.environ.get('ProgramFiles(x86)', ''),
                 os.environ.get('ProgramFiles', '')):
        for sub in ('Programs\\Inno Setup 6', 'Inno Setup 6'):
            p = os.path.join(base, sub, 'ISCC.exe')
            if os.path.exists(p):
                return p
    sys.exit('ISCC.exe (Inno Setup 6) not found, pass --iscc')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--build', default=os.path.join(SRC, '..', 'build'))
    ap.add_argument('--install', default=os.path.join(SRC, '..', 'install'))
    ap.add_argument('--iscc')
    ap.add_argument('--no-zip', action='store_true')
    args = ap.parse_args()
    build = os.path.normpath(args.build)
    install = os.path.normpath(args.install)

    if not os.path.exists(os.path.join(install, 'bin', 'Lightspeed.exe')):
        sys.exit('%s has no bin\\Lightspeed.exe, run cmake --install first' % install)

    # the Python runtime of the AI helper
    if not os.path.exists(os.path.join(install, 'share', 'darktable', 'lightspeed', 'ai', 'python', 'python.exe')):
        subprocess.check_call([sys.executable, os.path.join(HERE, 'bundle_python.py'), '--install', install])

    # licenses of the bundled libraries (MSYS2 packages): THIRD_PARTY_NOTICES.md
    # and share/licenses, made in the MSYS2 shell that knows the packages
    msys_bash = os.environ.get('MSYS2_BASH', r'C:\msys64\usr\bin\bash.exe')
    env = dict(os.environ, MSYSTEM='UCRT64', CHERE_INVOKING='1', MSYS2_PATH_TYPE='minimal')
    script = os.path.join(SRC, 'tools', 'lightspeed', 'third_party.py').replace(os.sep, '/')
    subprocess.check_call([msys_bash, '-lc', 'python "%s" "%s"' % (script, install.replace(os.sep, '/'))],
                          env=env)

    cache = cmake_cache(build)
    version = lightspeed_version()

    lines = ['; generated by make_installer.py, do not edit']
    for ext in supported_extensions(build) + ['dng', 'tif', 'tiff', 'jpg', 'jpeg']:
        line = ('Root: HKA; Subkey: "Software\\Classes\\.%s\\OpenWithList\\Lightspeed.exe"; '
                'Flags: uninsdeletekey' % ext)
        if line not in lines:
            lines.append(line)
    with open(os.path.join(HERE, 'lightspeed_openwith.iss'), 'w', encoding='utf-8-sig') as f:
        f.write('\n'.join(lines) + '\n')

    # Inno Setup needs a BOM to read the Hebrew messages as UTF-8
    iss = os.path.join(HERE, 'lightspeed.iss')
    text = open(iss, encoding='utf-8-sig').read()
    with open(iss, 'w', encoding='utf-8-sig', newline='\r\n') as f:
        f.write(text)

    os.makedirs(DIST, exist_ok=True)
    cmd = [find_iscc(args.iscc), '/Q',
           '/DSourceTree=' + install,
           '/DMyAppVersion=' + version,
           '/DDarktableVersion=' + cache.get('PROJECT_VERSION', '5.6.1'),
           '/DGphotoVersion=' + cache.get('CPACK_NSIS_GPHOTO2_VERSION', '2.5.34'),
           '/DGphotoPortVersion=' + cache.get('CPACK_NSIS_GPHOTO2_PORT_VERSION', '0.12.2'),
           iss]
    print(' '.join(cmd))
    subprocess.check_call(cmd)
    setup = os.path.join(DIST, 'Lightspeed-%s-win64-setup.exe' % version)
    print('installer: %s (%.0f MB)' % (setup, os.path.getsize(setup) / 1e6))

    if not args.no_zip:
        # portable: unzip anywhere and run bin\Lightspeed.exe, settings and
        # library still go to %LOCALAPPDATA%\lightspeed
        portable = os.path.join(DIST, 'Lightspeed-%s-win64-portable.zip' % version)
        with zipfile.ZipFile(portable, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as z:
            for root, _, files in os.walk(install):
                for name in files:
                    full = os.path.join(root, name)
                    rel = os.path.relpath(full, install)
                    z.write(full, os.path.join('Lightspeed', rel))
        print('portable:  %s (%.0f MB)' % (portable, os.path.getsize(portable) / 1e6))


if __name__ == '__main__':
    main()
